name: mucke
description: music player
publish_to: none

version: 1.2.0+7

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  audio_service: ^0.18.7  # MIT
  audio_session: ^0.1.5  # MIT
  collection: ^1.17.0  # BSD 3
  drift: ^2.5.0  # MIT
  equatable: ^2.0.3  # MIT
  file_picker: ^5.2.5  # MIT
  fimber: ^0.6.1  # Apache 2.0
  fimber_io: ^0.6.6  # Apache 2.0
  flutter:
    sdk: flutter
  flutter_fimber: ^0.6.3  # Apache 2.0
  flutter_mobx: ^2.0.0  # MIT
  flutter_speed_dial: ^6.2.0  # MIT
  get_it: ^7.1.3  # MIT
  just_audio: ^0.9.18  # MIT
  mobx: 2.1.3  # MIT
  on_audio_query: ^2.6.1  # BSD 3
  palette_generator: ^0.3.3+2  # BSD 3
  path: ^1.8.0  # BSD 3
  path_provider: ^2.0.2  # BSD 3
  permission_handler: ^10.2.0  # MIT
  provider: ^6.0.2  # MIT
  reorderables: ^0.6.0  # MIT
  sqlite3_flutter_libs: ^0.5.0  # MIT
  string_similarity: ^2.0.0  # MIT

dev_dependencies:
  build_runner: ^2.3.3  # BSD 3
  drift_dev: ^2.5.0  # MIT
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3  # MIT


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family:  MuckeIcons
      fonts:
        - asset: fonts/MuckeIcons.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
